development: adapter: mysql
  encoding: utf8
  database: MarketOfTheBeast
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: MarketOfTheBeast
  pool: 5
  username: root
  password:  "!elrenoSUBWAY1"
  host: localhost

production:
  adapter: sqlite3
  database: db/production.db
  pool: 5
  timeout: 5000
