development:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: marketofthebeast
  password: "Vityifewd2"
  host: marketofthebeast.db.8144713.hostedresource.com

test:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: marketofthebeast
  password: "Vityifewd2"
  host: marketofthebeast.db.8144713.hostedresource.com

production:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: marketofthebeast
  password: "Vityifewd2"
  host: marketofthebeast.db.8144713.hostedresource.com
