development:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: marketofthebeast
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
