development:
  adapter: mysql
  encoding: utf8
  database: MarketOfTheBeast
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: MarketOfTheBeast
  pool: 5
  username: root
  password:  "!elrenoSUBWAY1"
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: MarketOfTheBeast_Production
  pool: 5
  username: root
  password: "!elrenoSUBWAY1"
  host: localhost
